spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/SSM?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      aop-patterns: com.springboot08.*  #监控SpringBean
      filters: stat,wall # 底层开启功能，stat（sql监控），wall（防火墙）
      stat-view-servlet:  #配置监控页
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      web-stat-filter: #监控web
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false


